image: python:3.6-alpine

stages:
  - test
  - docu  
  - deploy

run_tests3.6:
  stage: test
  script:
    - pip install .
    - cd tests
    - python -m unittest discover -s .

run_tests2.7:
  image: python:2.7-alpine
  stage: test
  script:
    - pip install .
    - cd tests
    - python -m unittest discover -s .

deploy_staging:
  stage: deploy
  variables:
    TWINE_USERNAME: $STAGING_USERNAME # set in gitlab
    TWINE_PASSWORD: $STAGING_PASSWORD
  script:
    # replace https://blackout-technologies.github.io/btnexus-node-python with https://blackout-technologies.github.io/btnexus-node-python/[VERSION]
    - export VERSION=$(cat VERSION).$CI_PIPELINE_IID
    - echo $VERSION > VERSION #TODO: add to production
    - cat VERSION
    - sed -i 's/https:\/\/blackout-technologies.github.io\/btnexus-node-python/https:\/\/blackout-technologies.github.io\/btnexus-node-python\/'$VERSION'/g' README.md
    - pip install twine==2.0
    - python setup.py sdist
    - twine upload --verbose --repository-url https://test.pypi.org/legacy/ dist/*
  only:
    - develop

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    # replace https://blackout-technologies.github.io/btnexus-node-python with https://blackout-technologies.github.io/btnexus-node-python/[VERSION]
    - export VERSION=$(cat VERSION).$CI_PIPELINE_IID
    - sed -i 's/https:\/\/blackout-technologies.github.io\/btnexus-node-python/https:\/\/blackout-technologies.github.io\/btnexus-node-python\/'$VERSION'/g' README.md
    - pip install twine==2.0
    - python setup.py sdist
    - twine upload --verbose dist/*
  only:
    - master    

docu_staging:
  stage: docu
  variables:
    DOCUREPO: https://$GITUSER:$GITPW@github.com/Blackout-Technologies/Blackout-Technologies.github.io.git
    DOCUFOLDER: Blackout-Technologies.github.io
  script:
    - export VERSION=$(cat VERSION).$CI_PIPELINE_IID
    - apk update && apk upgrade && apk add --virtual build-dependencies build-base gcc wget git tree
    - git config --global user.email "dev@blackout.ai"
    - git config --global user.name "The Docs Guy"
    - git clone $DOCUREPO
    # install sphinx and the module!
    - pip install sphinx
    - pip install sphinx_rtd_theme
    - pip install .
    # remove the folder before to make sure to get rid of fragments
    - rm -rf _doc
    - sphinx-apidoc -efFMa -H btnexus-node-python -A "Blackout Technologies" -t doc/ -o _doc/ . tests nexus examples setup.py
    - cd _doc
    # removing 'btnexus-node-python' because it is not compatible for import
    - sed -i 's/btnexus-node-python.//g' btnexus-node-python.bt*
    - make html
    - cd -
    # copy docu into Blackout-Technologies.github.io
    - mkdir -p $DOCUFOLDER/$CI_PROJECT_TITLE/$VERSION
    - cp -r _doc/_build/html/* $DOCUFOLDER/$CI_PROJECT_TITLE/$VERSION
    - cd $DOCUFOLDER/$CI_PROJECT_TITLE
    - tree -d -H '.' -T 'VERSIONS' -L 1 --noreport --charset utf-8 > index.html
    - touch .nojekyll
    - cd -
    # cd into Blackout-Technologies.github.io
    - cd $DOCUFOLDER
    - git add -A
    - git commit -m "$CI_COMMIT_MESSAGE"
    - git push $DOCUREPO
  only:
    - develop
    - master

