image: python:3.6-alpine

stages:
  - deploy

before_script:
   - pip install twine # maybe better flit
   - python setup.py sdist

deploy_staging:
  stage: deploy
  variables:
    TWINE_USERNAME: $STAGING_USERNAME # set in gitlab
    TWINE_PASSWORD: $STAGING_PASSWORD
  script:
    - twine upload --repository-url https://test.pypi.org/legacy/ dist/*
  only:
    - develop

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - twine upload dist/*
  only:
    - master