image: python:3.6-alpine

stages:
  - build
  - test
  - deploy
  - docu

# build_package:
#   stage: build
#   script:
#     - pip install .

# run_tests:
#   stage: test
#   script:
#     - pip install .
#     - cd tests
#     #- python -m unittest discover -s .

# deploy_staging:
#   stage: deploy
#   variables:
#     TWINE_USERNAME: $STAGING_USERNAME # set in gitlab
#     TWINE_PASSWORD: $STAGING_PASSWORD
#   script:
  # TODO: replace https://blackout-technologies.github.io/btnexus-node-python with https://blackout-technologies.github.io/btnexus-node-python/[VERSION]
#     - pip install twine==2.0
#     - python setup.py sdist
#     - twine upload --verbose --repository-url https://test.pypi.org/legacy/ dist/*
#   only:
#     - develop


docu_staging:
  stage: docu
  variables:
    DOCUREPO: https://$GITUSER:$GITPW@github.com/Blackout-Technologies/Blackout-Technologies.github.io.git
    _STR: _
    VERSION: DEV     # TODO: get VERSION from VERSION file for production
    DOCUBUILDFOLDER: $CI_PROJECT_TITLE$/$VERSION #$CI_PROJECT_TITLE/$VERSION 
    DOCUFOLDER: Blackout-Technologies.github.io
  script:
    - apk update && apk upgrade && apk add --virtual build-dependencies build-base gcc wget git
    - git config --global user.email "dev@blackout.ai"
    - git config --global user.name "The Docs Guy"
    - git clone $DOCUREPO
    # install sphinx and the module!
    - pip install sphinx
    - pip install sphinx_rtd_theme
    - pip install .
    # remove the folder before to make sure to get rid of fragments
    - rm -rf _doc
    - sphinx-apidoc -efFMa -H btnexus-node-python -A "Blackout Technologies" -t doc/ -o _doc/ . tests nexus examples setup.py
    - cd _doc
    # removing 'btnexus-node-python' because it is not compatible for import
    - sed -i 's/btnexus-node-python.//g' btnexus-node-python.bt*
    - make html
    - mkdir -p $DOCUBUILDFOLDER
    - ls -ah
    - cp -r _build/html/* $DOCUBUILDFOLDER
    # copy docu into Blackout-Technologies.github.io
    - echo $DOCUBUILDFOLDER
    - ls $DOCUBUILDFOLDER
    - echo $DOCUFOLDER    
    - ls ../$DOCUFOLDER
    - cp -r $DOCUBUILDFOLDER ../$DOCUFOLDER/$CI_PROJECT_TITLE
    # cd into Blackout-Technologies.github.io
    - cd ../$DOCUFOLDER
    - git add -A
    - git commit -m "$CI_COMMIT_MESSAGE"
    - git push $DOCUREPO
  only:
    - develop

# deploy_production:
#   stage: deploy
#   variables:
#     TWINE_USERNAME: $PRODUCTION_USERNAME
#     TWINE_PASSWORD: $PRODUCTION_PASSWORD
#   script:
#     - pip install twine==2.0
#     - python setup.py sdist
#     - twine upload --verbose dist/*
#   only:
#     - master